title = "Duc Nguyen"
baseURL = "https://ducng.github.io/"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
#themesDir = "../.."

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicon.svg"
  site_logo = "favicon.svg"
  description = "My personal blog"
  facebook = ""
  # twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = "https://github.com/DucNg/"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/nguyen-d/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = "https://ducng.github.io/index.xml"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 10
  post_content_classes = "Avenir bg-near-white tj"
  page_content_classes = "tj"

[[cascade]]
  featured_image = "banner.webp"