title = "Duc Nguyen"
baseURL = "https://ducng.github.io/"
languageCode = "en-us"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
#themesDir = "../.."

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = false

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
favicon = "favicon.svg"
site_logo = ""
description = "My personal blog"
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 10
post_content_classes = "Avenir bg-near-white tj"
page_content_classes = "tj"

[[cascade]]
featured_image = "banner.webp"

[params.ananke.social]
icon_path = "ananke/socials/%s.svg"

[params.ananke.social.follow]
# new_window_icon = true # show a little "opens in new window" icon next to the link
# add networks to this list in your local config to enable them, remove them to disable them.
networks = [
  "github",
  "linkedin",
  "rss"
]

[params.ananke.social.share]
icons = true # show icons for each share link
sharetext = true # show the share text
# add networks to this list in your local config to enable them, remove them to disable them.
networks = [
  "x-twitter",
  "bluesky",
  "linkedin",
  "hackernews",
  "email"
]

[params.ananke.social.github]
username = "DucNg"

[params.ananke.social.linkedin]
username = "nguyen-d"

[params.ananke.social.rss]
profileLink = "https://ducng.github.io/index.xml"
